export const FETCH_CHARACTERS_SUCCESS = "FETCH_CHARACTERS_SUCCESS";
export const FETCH_CHARACTERS_FAIL = "FETCH_CHARACTERS_FAIL";
export const FETCH_EPISODE_SUCCESS = "FETCH_EPISODE_SUCCESS";
export const FETCH_EPISODE_FAIL = "FETCH_EPISODE_FAIL";